[general]
import = [
    "~/.config/alacritty/themes/themes/ashes_dark.toml"
]

[window]
dimensions = { columns = 100, lines = 25 }
opacity = 0.9

[font]
size = 14

[[keyboard.bindings]]
    action = "SpawnNewInstance"
    key    = "N"
    mods   = "Control|Shift"

