[[manager.prepend_keymap]]
on   = "<Enter>"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[manager.prepend_keymap]]
on   = "l"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[manager.prepend_keymap]]
on   = "i"
run  = "cd --interactive"
desc = "go"

[[manager.prepend_keymap]]
on   = [ "g", "m" ]
run  = "cd /run/media/viktor"
desc = "Enter to connected flash drive"

[[manager.prepend_keymap]]
on  = "y"
run = [
 '''
 shell --silent --confirm --stdin -- 
 for file in "$@"; do 
   printf 'file://%s\n' "$(realpath "$file")"; 
 done | xclip -selection clipboard -t text/uri-list
 ''',
 "yank"
]

[[manager.prepend_keymap]]
on   = "T"
run  = "plugin toggle-pane min-preview"
desc = "Show or hide the preview pane"

[[manager.prepend_keymap]]
on   = "T"
run  = "plugin toggle-pane max-preview"
desc = "Maximize or restore the preview pane"
