[opener]
play = [
	{ run = 'vlc "$@"', orphan = true, for = "unix" },
]
edit = [
	{ run = '$EDITOR "$@"', block = true, for = "unix" },
]
open = [
    { run = 'xdg-open "$@"', desc = "Open" },
]

[plugin]
prepend_previewers = [
  { name = "*.md", run = "glow" },
]
